name: Plinko
run-name: Plinko Actions
on: [push]
jobs:
    
  build:
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Build jar file
        run: |
          make build

  test:
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          make test
  
  lint:
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Lint the project
        run: |
          make lint
  
  package:
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Build Jar File
        run: |
          make build
      - name: Build deb package
        run: |
          make package
      - name: Save deb package
        uses: actions/upload-artifact@v4
        with:
          name: Plinko package
          path: plinko-v1.0.0.deb
